Part 2: implement handling no hooks
babel-plugin-ember-test-metadata/babel-plugin-ember-test-metadata pull request #15
Opened 2021-07-19 18:36 UTC by glnster

Address "no hooks" case.
If the function passed into module() has no arg passed (e.g. no "hooks") then pass in a "hooks" arg.

Testing done:
- this stand-alone repo (added test)
- a simple ember app (added similar test)
- a test file in a large, private ember app, that doesn't pass in any "hooks"

2021-07-19 18:55 UTC, ckundo commented
Should this be opened again `master`?

2021-07-19 20:10 UTC, scalvert requested changes

2021-07-19 20:10 UTC, scalvert commented on src/index.js
> +            const moduleFunction = moduleArgs[1];
I feel like you could probably destructure the array above with this and line 197 below.

2021-07-19 20:11 UTC, scalvert commented
> Should this be opened again `master`?

No, because it's building off https://github.com/babel-plugin-ember-test-metadata/babel-plugin-ember-test-metadata/pull/14. Once that's merged, that would be the time to change the base.

2021-07-21 16:21 UTC, glnster commented
Closing this PR. PR #14 now includes addressing the "no hooks" case.

2021-07-21 16:21 UTC, closed without merging